//! Generated from the mod's own built assets — do not edit by hand.
//!
//! `blockstates/` and `items/` in `assets/mysticalagriculture` enumerate the two
//! registries exactly, which is what the registry snapshot has to reproduce: it
//! replaces the client's registry, so a missing or extra name breaks the join.
//!
//! Block properties come from the same blockstate files, sorted by name because that
//! is the order Minecraft assigns state ids in. Their product is the state count, and
//! it has to match the client's or the two ends disagree about which state is which.

/// A property a block's states vary over.
pub struct Property {
    /// Property name, as the mod declares it.
    pub name: &'static str,
    /// Every value it can take, in order.
    pub values: &'static [&'static str],
}

/// A block the mod registers.
pub struct BlockEntry {
    /// Path part of the id, without the namespace.
    pub name: &'static str,
    /// The vanilla block it is modelled on.
    pub template: &'static str,
    /// The properties its states vary over.
    pub properties: &'static [Property],
}

/// Every block the mod registers.
pub const BLOCKS: [BlockEntry; 212] = [
    BlockEntry { name: "air_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "aluminum_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "amethyst_bronze_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "amethyst_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "apatite_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "aquamarine_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "armadillo_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "awakened_supremium_block", template: "stone", properties: &[] },
    BlockEntry { name: "awakened_supremium_farmland", template: "farmland", properties: &[Property { name: "moisture", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "awakened_supremium_gemstone_block", template: "stone", properties: &[] },
    BlockEntry { name: "awakened_supremium_growth_accelerator", template: "stone", properties: &[] },
    BlockEntry { name: "awakened_supremium_ingot_block", template: "stone", properties: &[] },
    BlockEntry { name: "awakening_altar", template: "stone", properties: &[] },
    BlockEntry { name: "awakening_pedestal", template: "stone", properties: &[] },
    BlockEntry { name: "basalt_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "basalz_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "blaze_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "blazing_crystal_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "blitz_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "blizz_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "brass_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "breeze_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "bronze_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "certus_quartz_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "chicken_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "coal_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "cobalt_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "compressed_iron_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "conductive_alloy_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "constantan_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "copper_alloy_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "copper_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "coral_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "cow_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "creeper_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "cyanite_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "dark_steel_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "deepslate_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "deepslate_inferium_ore", template: "stone", properties: &[] },
    BlockEntry { name: "deepslate_prosperity_ore", template: "stone", properties: &[] },
    BlockEntry { name: "diamond_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "dirt_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "draconium_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "dye_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "earth_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "electrum_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "elementium_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "emerald_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "enchanter", template: "stone", properties: &[Property { name: "facing", values: &["north", "south", "west", "east"] }, ] },
    BlockEntry { name: "end_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "end_steel_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "enderium_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "enderman_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "energetic_alloy_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "energized_steel_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "essence_vessel", template: "stone", properties: &[] },
    BlockEntry { name: "experience_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "fiery_ingot_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "fire_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "fish_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "fluix_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "fluorite_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "flux_infused_gem_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "flux_infused_ingot_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "furnace", template: "stone", properties: &[Property { name: "facing", values: &["north", "south", "west", "east"] }, Property { name: "running", values: &["false", "true"] }, ] },
    BlockEntry { name: "ghast_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "glowstone_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "gold_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "grains_of_infinity_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "graphite_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "harvester", template: "stone", properties: &[Property { name: "facing", values: &["east", "north", "south", "west"] }, Property { name: "running", values: &["false", "true"] }, ] },
    BlockEntry { name: "hepatizon_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "honey_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "hop_graphite_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "ice_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "imperium_block", template: "stone", properties: &[] },
    BlockEntry { name: "imperium_farmland", template: "farmland", properties: &[Property { name: "moisture", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "imperium_gemstone_block", template: "stone", properties: &[] },
    BlockEntry { name: "imperium_growth_accelerator", template: "stone", properties: &[] },
    BlockEntry { name: "imperium_ingot_block", template: "stone", properties: &[] },
    BlockEntry { name: "inferium_block", template: "stone", properties: &[] },
    BlockEntry { name: "inferium_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "inferium_farmland", template: "farmland", properties: &[Property { name: "moisture", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "inferium_gemstone_block", template: "stone", properties: &[] },
    BlockEntry { name: "inferium_growth_accelerator", template: "stone", properties: &[] },
    BlockEntry { name: "inferium_ingot_block", template: "stone", properties: &[] },
    BlockEntry { name: "inferium_ore", template: "stone", properties: &[] },
    BlockEntry { name: "infusion_altar", template: "stone", properties: &[] },
    BlockEntry { name: "infusion_pedestal", template: "stone", properties: &[] },
    BlockEntry { name: "invar_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "iridium_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "iron_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "ironwood_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "knightmetal_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "lapis_lazuli_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "lead_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "limestone_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "lumium_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "machine_frame", template: "stone", properties: &[] },
    BlockEntry { name: "manasteel_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "manyullyn_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "marble_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "menril_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "mystical_flower_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "mystical_mob_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "mystical_resource_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "nature_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "nether_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "nether_quartz_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "netherite_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "nickel_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "niotic_crystal_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "obsidian_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "ore_infuser", template: "stone", properties: &[Property { name: "facing", values: &["east", "north", "south", "west"] }, Property { name: "running", values: &["false", "true"] }, ] },
    BlockEntry { name: "osmium_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "peridot_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "phantom_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "pig_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "pig_iron_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "platinum_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "prismarine_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "prosperity_block", template: "stone", properties: &[] },
    BlockEntry { name: "prosperity_gemstone_block", template: "stone", properties: &[] },
    BlockEntry { name: "prosperity_ingot_block", template: "stone", properties: &[] },
    BlockEntry { name: "prosperity_ore", template: "stone", properties: &[] },
    BlockEntry { name: "prudentium_block", template: "stone", properties: &[] },
    BlockEntry { name: "prudentium_farmland", template: "farmland", properties: &[Property { name: "moisture", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "prudentium_gemstone_block", template: "stone", properties: &[] },
    BlockEntry { name: "prudentium_growth_accelerator", template: "stone", properties: &[] },
    BlockEntry { name: "prudentium_ingot_block", template: "stone", properties: &[] },
    BlockEntry { name: "pulsating_alloy_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "quartz_enriched_iron_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "queens_slime_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "rabbit_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "redstone_alloy_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "redstone_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "refined_glowstone_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "refined_obsidian_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "rock_crystal_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "rose_gold_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "rubber_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "ruby_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "saltpeter_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "sapphire_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "sculk_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "seed_reprocessor", template: "stone", properties: &[Property { name: "facing", values: &["east", "north", "south", "west"] }, Property { name: "running", values: &["false", "true"] }, ] },
    BlockEntry { name: "sheep_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "signalum_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "silicon_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "silver_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "skeleton_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "sky_stone_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "slime_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "slimesteel_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "soul_extractor", template: "stone", properties: &[Property { name: "facing", values: &["east", "north", "south", "west"] }, Property { name: "running", values: &["false", "true"] }, ] },
    BlockEntry { name: "soul_glass", template: "glass", properties: &[] },
    BlockEntry { name: "soularium_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "soulium_block", template: "stone", properties: &[] },
    BlockEntry { name: "soulium_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "soulium_gemstone_block", template: "stone", properties: &[] },
    BlockEntry { name: "soulium_ingot_block", template: "stone", properties: &[] },
    BlockEntry { name: "soulium_ore", template: "stone", properties: &[] },
    BlockEntry { name: "soulium_spawner", template: "stone", properties: &[Property { name: "facing", values: &["east", "north", "south", "west"] }, Property { name: "running", values: &["false", "true"] }, ] },
    BlockEntry { name: "soulstone", template: "stone", properties: &[] },
    BlockEntry { name: "soulstone_bricks", template: "stone", properties: &[] },
    BlockEntry { name: "soulstone_bricks_slab", template: "stone", properties: &[Property { name: "type", values: &["bottom", "top", "double"] }, ] },
    BlockEntry { name: "soulstone_bricks_stairs", template: "stone", properties: &[Property { name: "facing", values: &["east", "west", "south", "north"] }, Property { name: "half", values: &["bottom", "top"] }, Property { name: "shape", values: &["straight", "outer_right", "outer_left", "inner_right", "inner_left"] }, ] },
    BlockEntry { name: "soulstone_bricks_wall", template: "stone", properties: &[] },
    BlockEntry { name: "soulstone_chiseled_bricks", template: "stone", properties: &[] },
    BlockEntry { name: "soulstone_cobble", template: "stone", properties: &[] },
    BlockEntry { name: "soulstone_cobble_slab", template: "stone", properties: &[Property { name: "type", values: &["bottom", "top", "double"] }, ] },
    BlockEntry { name: "soulstone_cobble_stairs", template: "stone", properties: &[Property { name: "facing", values: &["east", "west", "south", "north"] }, Property { name: "half", values: &["bottom", "top"] }, Property { name: "shape", values: &["straight", "outer_right", "outer_left", "inner_right", "inner_left"] }, ] },
    BlockEntry { name: "soulstone_cobble_wall", template: "stone", properties: &[] },
    BlockEntry { name: "soulstone_cracked_bricks", template: "stone", properties: &[] },
    BlockEntry { name: "soulstone_slab", template: "stone", properties: &[Property { name: "type", values: &["bottom", "top", "double"] }, ] },
    BlockEntry { name: "soulstone_smooth", template: "stone", properties: &[] },
    BlockEntry { name: "soulstone_smooth_slab", template: "stone", properties: &[Property { name: "type", values: &["bottom", "top", "double"] }, ] },
    BlockEntry { name: "soulstone_stairs", template: "stone", properties: &[Property { name: "facing", values: &["east", "west", "south", "north"] }, Property { name: "half", values: &["bottom", "top"] }, Property { name: "shape", values: &["straight", "outer_right", "outer_left", "inner_right", "inner_left"] }, ] },
    BlockEntry { name: "spider_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "spirited_crystal_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "squid_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "starmetal_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "steel_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "steeleaf_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "stone_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "sulfur_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "supremium_block", template: "stone", properties: &[] },
    BlockEntry { name: "supremium_farmland", template: "farmland", properties: &[Property { name: "moisture", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "supremium_gemstone_block", template: "stone", properties: &[] },
    BlockEntry { name: "supremium_growth_accelerator", template: "stone", properties: &[] },
    BlockEntry { name: "supremium_ingot_block", template: "stone", properties: &[] },
    BlockEntry { name: "terrasteel_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "tertium_block", template: "stone", properties: &[] },
    BlockEntry { name: "tertium_farmland", template: "farmland", properties: &[Property { name: "moisture", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "tertium_gemstone_block", template: "stone", properties: &[] },
    BlockEntry { name: "tertium_growth_accelerator", template: "stone", properties: &[] },
    BlockEntry { name: "tertium_ingot_block", template: "stone", properties: &[] },
    BlockEntry { name: "tin_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "tinkering_table", template: "stone", properties: &[] },
    BlockEntry { name: "turtle_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "uraninite_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "uranium_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "vibrant_alloy_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "water_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "wither_skeleton_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "witherproof_block", template: "stone", properties: &[] },
    BlockEntry { name: "witherproof_bricks", template: "stone", properties: &[] },
    BlockEntry { name: "witherproof_glass", template: "glass", properties: &[] },
    BlockEntry { name: "wood_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "yellorium_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "zinc_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
    BlockEntry { name: "zombie_crop", template: "wheat", properties: &[Property { name: "age", values: &["0", "1", "2", "3", "4", "5", "6", "7"] }, ] },
];

/// Every item the mod registers, with the vanilla item each is modelled on.
pub const ITEMS: [(&str, &str); 605] = [
    ("absorption_i_augment", "diamond"),
    ("absorption_ii_augment", "diamond"),
    ("absorption_iii_augment", "diamond"),
    ("absorption_iv_augment", "diamond"),
    ("absorption_v_augment", "diamond"),
    ("air_agglomeratio", "diamond"),
    ("air_essence", "diamond"),
    ("air_seeds", "wheat_seeds"),
    ("aluminum_essence", "diamond"),
    ("aluminum_seeds", "wheat_seeds"),
    ("amethyst_bronze_essence", "diamond"),
    ("amethyst_bronze_seeds", "wheat_seeds"),
    ("amethyst_essence", "diamond"),
    ("amethyst_seeds", "wheat_seeds"),
    ("apatite_essence", "diamond"),
    ("apatite_seeds", "wheat_seeds"),
    ("aquamarine_essence", "diamond"),
    ("aquamarine_seeds", "wheat_seeds"),
    ("armadillo_essence", "diamond"),
    ("armadillo_seeds", "wheat_seeds"),
    ("attack_aoe_i_augment", "diamond"),
    ("attack_aoe_ii_augment", "diamond"),
    ("attack_aoe_iii_augment", "diamond"),
    ("augment", "diamond"),
    ("awakened_supremium_axe", "diamond_axe"),
    ("awakened_supremium_block", "diamond"),
    ("awakened_supremium_boots", "diamond_boots"),
    ("awakened_supremium_bow", "bow"),
    ("awakened_supremium_chestplate", "diamond_chestplate"),
    ("awakened_supremium_crossbow", "diamond"),
    ("awakened_supremium_essence", "diamond"),
    ("awakened_supremium_farmland", "diamond"),
    ("awakened_supremium_fishing_rod", "diamond"),
    ("awakened_supremium_gemstone", "diamond"),
    ("awakened_supremium_gemstone_block", "diamond"),
    ("awakened_supremium_growth_accelerator", "diamond"),
    ("awakened_supremium_helmet", "diamond_helmet"),
    ("awakened_supremium_hoe", "diamond_hoe"),
    ("awakened_supremium_ingot", "diamond"),
    ("awakened_supremium_ingot_block", "diamond"),
    ("awakened_supremium_leggings", "diamond_leggings"),
    ("awakened_supremium_nugget", "diamond"),
    ("awakened_supremium_pickaxe", "diamond_pickaxe"),
    ("awakened_supremium_scythe", "diamond"),
    ("awakened_supremium_shears", "diamond"),
    ("awakened_supremium_shovel", "diamond_shovel"),
    ("awakened_supremium_sickle", "diamond"),
    ("awakened_supremium_spear", "diamond"),
    ("awakened_supremium_staff", "diamond"),
    ("awakened_supremium_sword", "diamond_sword"),
    ("awakened_supremium_upgrade", "diamond"),
    ("awakened_supremium_watering_can", "diamond"),
    ("awakening_altar", "diamond"),
    ("awakening_pedestal", "diamond"),
    ("basalt_essence", "diamond"),
    ("basalt_seeds", "wheat_seeds"),
    ("basalz_essence", "diamond"),
    ("basalz_seeds", "wheat_seeds"),
    ("blank_augment", "diamond"),
    ("blank_record", "diamond"),
    ("blank_skull", "diamond"),
    ("blaze_essence", "diamond"),
    ("blaze_seeds", "wheat_seeds"),
    ("blazing_crystal_essence", "diamond"),
    ("blazing_crystal_seeds", "wheat_seeds"),
    ("blindness_resistance_augment", "diamond"),
    ("blitz_essence", "diamond"),
    ("blitz_seeds", "wheat_seeds"),
    ("blizz_essence", "diamond"),
    ("blizz_seeds", "wheat_seeds"),
    ("brass_essence", "diamond"),
    ("brass_seeds", "wheat_seeds"),
    ("breeze_essence", "diamond"),
    ("breeze_seeds", "wheat_seeds"),
    ("bronze_essence", "diamond"),
    ("bronze_seeds", "wheat_seeds"),
    ("certus_quartz_essence", "diamond"),
    ("certus_quartz_seeds", "wheat_seeds"),
    ("chicken_essence", "diamond"),
    ("chicken_seeds", "wheat_seeds"),
    ("coal_essence", "diamond"),
    ("coal_seeds", "wheat_seeds"),
    ("cobalt_essence", "diamond"),
    ("cobalt_seeds", "wheat_seeds"),
    ("cognizant_dust", "diamond"),
    ("compressed_iron_essence", "diamond"),
    ("compressed_iron_seeds", "wheat_seeds"),
    ("conductive_alloy_essence", "diamond"),
    ("conductive_alloy_seeds", "wheat_seeds"),
    ("constantan_essence", "diamond"),
    ("constantan_seeds", "wheat_seeds"),
    ("copper_alloy_essence", "diamond"),
    ("copper_alloy_seeds", "wheat_seeds"),
    ("copper_essence", "diamond"),
    ("copper_scythe", "diamond"),
    ("copper_seeds", "wheat_seeds"),
    ("copper_sickle", "diamond"),
    ("coral_agglomeratio", "diamond"),
    ("coral_essence", "diamond"),
    ("coral_seeds", "wheat_seeds"),
    ("cow_essence", "diamond"),
    ("cow_seeds", "wheat_seeds"),
    ("creative_soulium_dagger", "diamond"),
    ("creeper_essence", "diamond"),
    ("creeper_seeds", "wheat_seeds"),
    ("cyanite_essence", "diamond"),
    ("cyanite_seeds", "wheat_seeds"),
    ("dark_steel_essence", "diamond"),
    ("dark_steel_seeds", "wheat_seeds"),
    ("deepslate_essence", "diamond"),
    ("deepslate_inferium_ore", "diamond"),
    ("deepslate_prosperity_ore", "diamond"),
    ("deepslate_seeds", "wheat_seeds"),
    ("diamond_essence", "diamond"),
    ("diamond_scythe", "diamond"),
    ("diamond_seeds", "wheat_seeds"),
    ("diamond_sickle", "diamond"),
    ("dirt_essence", "diamond"),
    ("dirt_seeds", "wheat_seeds"),
    ("draconium_essence", "diamond"),
    ("draconium_seeds", "wheat_seeds"),
    ("dye_agglomeratio", "diamond"),
    ("dye_essence", "diamond"),
    ("dye_seeds", "wheat_seeds"),
    ("earth_agglomeratio", "diamond"),
    ("earth_essence", "diamond"),
    ("earth_seeds", "wheat_seeds"),
    ("electrum_essence", "diamond"),
    ("electrum_seeds", "wheat_seeds"),
    ("elementium_essence", "diamond"),
    ("elementium_seeds", "wheat_seeds"),
    ("emerald_essence", "diamond"),
    ("emerald_seeds", "wheat_seeds"),
    ("enchanter", "diamond"),
    ("end_agglomeratio", "diamond"),
    ("end_essence", "diamond"),
    ("end_seeds", "wheat_seeds"),
    ("end_steel_essence", "diamond"),
    ("end_steel_seeds", "wheat_seeds"),
    ("enderium_essence", "diamond"),
    ("enderium_seeds", "wheat_seeds"),
    ("enderman_essence", "diamond"),
    ("enderman_seeds", "wheat_seeds"),
    ("energetic_alloy_essence", "diamond"),
    ("energetic_alloy_seeds", "wheat_seeds"),
    ("energized_steel_essence", "diamond"),
    ("energized_steel_seeds", "wheat_seeds"),
    ("essence_diamond", "diamond"),
    ("essence_dust", "diamond"),
    ("essence_flame", "diamond"),
    ("essence_gem", "diamond"),
    ("essence_ingot", "diamond"),
    ("essence_quartz", "diamond"),
    ("essence_rock", "diamond"),
    ("essence_rod", "diamond"),
    ("essence_tall_gem", "diamond"),
    ("essence_vessel", "diamond"),
    ("experience_capsule", "diamond"),
    ("experience_droplet", "diamond"),
    ("experience_essence", "diamond"),
    ("experience_seeds", "wheat_seeds"),
    ("fertilized_essence", "diamond"),
    ("fiery_ingot_essence", "diamond"),
    ("fiery_ingot_seeds", "wheat_seeds"),
    ("fire_agglomeratio", "diamond"),
    ("fire_essence", "diamond"),
    ("fire_resistance_augment", "diamond"),
    ("fire_seeds", "wheat_seeds"),
    ("fish_essence", "diamond"),
    ("fish_seeds", "wheat_seeds"),
    ("flight_augment", "diamond"),
    ("fluix_essence", "diamond"),
    ("fluix_seeds", "wheat_seeds"),
    ("fluorite_essence", "diamond"),
    ("fluorite_seeds", "wheat_seeds"),
    ("flux_infused_gem_essence", "diamond"),
    ("flux_infused_gem_seeds", "wheat_seeds"),
    ("flux_infused_ingot_essence", "diamond"),
    ("flux_infused_ingot_seeds", "wheat_seeds"),
    ("furnace", "diamond"),
    ("ghast_essence", "diamond"),
    ("ghast_seeds", "wheat_seeds"),
    ("glowstone_essence", "diamond"),
    ("glowstone_seeds", "wheat_seeds"),
    ("gold_essence", "diamond"),
    ("gold_seeds", "wheat_seeds"),
    ("golden_scythe", "diamond"),
    ("golden_sickle", "diamond"),
    ("grains_of_infinity_essence", "diamond"),
    ("grains_of_infinity_seeds", "wheat_seeds"),
    ("graphite_essence", "diamond"),
    ("graphite_seeds", "wheat_seeds"),
    ("guide_book", "diamond"),
    ("harvester", "diamond"),
    ("haste_i_augment", "diamond"),
    ("haste_ii_augment", "diamond"),
    ("haste_iii_augment", "diamond"),
    ("health_boost_i_augment", "diamond"),
    ("health_boost_ii_augment", "diamond"),
    ("health_boost_iii_augment", "diamond"),
    ("health_boost_iv_augment", "diamond"),
    ("health_boost_v_augment", "diamond"),
    ("hepatizon_essence", "diamond"),
    ("hepatizon_seeds", "wheat_seeds"),
    ("honey_agglomeratio", "diamond"),
    ("honey_essence", "diamond"),
    ("honey_seeds", "wheat_seeds"),
    ("hop_graphite_essence", "diamond"),
    ("hop_graphite_seeds", "wheat_seeds"),
    ("hostile_soulium_dagger", "diamond"),
    ("hunger_resistance_augment", "diamond"),
    ("ice_essence", "diamond"),
    ("ice_seeds", "wheat_seeds"),
    ("imperium_axe", "diamond_axe"),
    ("imperium_block", "diamond"),
    ("imperium_boots", "diamond_boots"),
    ("imperium_bow", "bow"),
    ("imperium_chestplate", "diamond_chestplate"),
    ("imperium_crossbow", "diamond"),
    ("imperium_essence", "diamond"),
    ("imperium_farmland", "diamond"),
    ("imperium_fishing_rod", "diamond"),
    ("imperium_gemstone", "diamond"),
    ("imperium_gemstone_block", "diamond"),
    ("imperium_growth_accelerator", "diamond"),
    ("imperium_helmet", "diamond_helmet"),
    ("imperium_hoe", "diamond_hoe"),
    ("imperium_ingot", "diamond"),
    ("imperium_ingot_block", "diamond"),
    ("imperium_leggings", "diamond_leggings"),
    ("imperium_nugget", "diamond"),
    ("imperium_pickaxe", "diamond_pickaxe"),
    ("imperium_scythe", "diamond"),
    ("imperium_shears", "diamond"),
    ("imperium_shovel", "diamond_shovel"),
    ("imperium_sickle", "diamond"),
    ("imperium_spear", "diamond"),
    ("imperium_staff", "diamond"),
    ("imperium_sword", "diamond_sword"),
    ("imperium_upgrade", "diamond"),
    ("imperium_watering_can", "diamond"),
    ("inferium_axe", "diamond_axe"),
    ("inferium_block", "diamond"),
    ("inferium_boots", "diamond_boots"),
    ("inferium_bow", "bow"),
    ("inferium_chestplate", "diamond_chestplate"),
    ("inferium_crossbow", "diamond"),
    ("inferium_essence", "diamond"),
    ("inferium_farmland", "diamond"),
    ("inferium_fishing_rod", "diamond"),
    ("inferium_gemstone", "diamond"),
    ("inferium_gemstone_block", "diamond"),
    ("inferium_growth_accelerator", "diamond"),
    ("inferium_helmet", "diamond_helmet"),
    ("inferium_hoe", "diamond_hoe"),
    ("inferium_ingot", "diamond"),
    ("inferium_ingot_block", "diamond"),
    ("inferium_leggings", "diamond_leggings"),
    ("inferium_nugget", "diamond"),
    ("inferium_ore", "diamond"),
    ("inferium_pickaxe", "diamond_pickaxe"),
    ("inferium_scythe", "diamond"),
    ("inferium_seeds", "wheat_seeds"),
    ("inferium_shears", "diamond"),
    ("inferium_shovel", "diamond_shovel"),
    ("inferium_sickle", "diamond"),
    ("inferium_spear", "diamond"),
    ("inferium_staff", "diamond"),
    ("inferium_sword", "diamond_sword"),
    ("inferium_upgrade", "diamond"),
    ("inferium_watering_can", "diamond"),
    ("infusion_altar", "diamond"),
    ("infusion_crystal", "diamond"),
    ("infusion_pedestal", "diamond"),
    ("invar_essence", "diamond"),
    ("invar_seeds", "wheat_seeds"),
    ("iridium_essence", "diamond"),
    ("iridium_seeds", "wheat_seeds"),
    ("iron_essence", "diamond"),
    ("iron_scythe", "diamond"),
    ("iron_seeds", "wheat_seeds"),
    ("iron_sickle", "diamond"),
    ("ironwood_essence", "diamond"),
    ("ironwood_seeds", "wheat_seeds"),
    ("jump_boost_i_augment", "diamond"),
    ("jump_boost_ii_augment", "diamond"),
    ("jump_boost_iii_augment", "diamond"),
    ("knightmetal_essence", "diamond"),
    ("knightmetal_seeds", "wheat_seeds"),
    ("lapis_lazuli_essence", "diamond"),
    ("lapis_lazuli_seeds", "wheat_seeds"),
    ("lead_essence", "diamond"),
    ("lead_seeds", "wheat_seeds"),
    ("limestone_essence", "diamond"),
    ("limestone_seeds", "wheat_seeds"),
    ("luck_i_augment", "diamond"),
    ("luck_ii_augment", "diamond"),
    ("luck_iii_augment", "diamond"),
    ("lumium_essence", "diamond"),
    ("lumium_seeds", "wheat_seeds"),
    ("machine_frame", "diamond"),
    ("manasteel_essence", "diamond"),
    ("manasteel_seeds", "wheat_seeds"),
    ("manyullyn_essence", "diamond"),
    ("manyullyn_seeds", "wheat_seeds"),
    ("marble_essence", "diamond"),
    ("marble_seeds", "wheat_seeds"),
    ("master_infusion_crystal", "diamond"),
    ("menril_essence", "diamond"),
    ("menril_seeds", "wheat_seeds"),
    ("mining_aoe_i_augment", "diamond"),
    ("mining_aoe_ii_augment", "diamond"),
    ("mining_aoe_iii_augment", "diamond"),
    ("mining_aoe_iv_augment", "diamond"),
    ("mining_fatigue_resistance_augment", "diamond"),
    ("mystical_fertilizer", "diamond"),
    ("mystical_flower_agglomeratio", "diamond"),
    ("mystical_flower_essence", "diamond"),
    ("mystical_flower_seeds", "wheat_seeds"),
    ("mystical_seeds", "wheat_seeds"),
    ("nature_agglomeratio", "diamond"),
    ("nature_essence", "diamond"),
    ("nature_seeds", "wheat_seeds"),
    ("nausea_resistance_augment", "diamond"),
    ("nether_agglomeratio", "diamond"),
    ("nether_essence", "diamond"),
    ("nether_quartz_essence", "diamond"),
    ("nether_quartz_seeds", "wheat_seeds"),
    ("nether_seeds", "wheat_seeds"),
    ("netherite_essence", "diamond"),
    ("netherite_scythe", "diamond"),
    ("netherite_seeds", "wheat_seeds"),
    ("netherite_sickle", "diamond"),
    ("nickel_essence", "diamond"),
    ("nickel_seeds", "wheat_seeds"),
    ("night_vision_augment", "diamond"),
    ("niotic_crystal_essence", "diamond"),
    ("niotic_crystal_seeds", "wheat_seeds"),
    ("no_fall_damage_augment", "diamond"),
    ("obsidian_essence", "diamond"),
    ("obsidian_seeds", "wheat_seeds"),
    ("ore_infuser", "diamond"),
    ("osmium_essence", "diamond"),
    ("osmium_seeds", "wheat_seeds"),
    ("passive_soulium_dagger", "diamond"),
    ("pathing_aoe_i_augment", "diamond"),
    ("pathing_aoe_ii_augment", "diamond"),
    ("pathing_aoe_iii_augment", "diamond"),
    ("pathing_aoe_iv_augment", "diamond"),
    ("peridot_essence", "diamond"),
    ("peridot_seeds", "wheat_seeds"),
    ("phantom_essence", "diamond"),
    ("phantom_seeds", "wheat_seeds"),
    ("pig_essence", "diamond"),
    ("pig_iron_essence", "diamond"),
    ("pig_iron_seeds", "wheat_seeds"),
    ("pig_seeds", "wheat_seeds"),
    ("platinum_essence", "diamond"),
    ("platinum_seeds", "wheat_seeds"),
    ("poison_resistance_augment", "diamond"),
    ("prismarine_agglomeratio", "diamond"),
    ("prismarine_essence", "diamond"),
    ("prismarine_seeds", "wheat_seeds"),
    ("prosperity_block", "diamond"),
    ("prosperity_gemstone", "diamond"),
    ("prosperity_gemstone_block", "diamond"),
    ("prosperity_ingot", "diamond"),
    ("prosperity_ingot_block", "diamond"),
    ("prosperity_nugget", "diamond"),
    ("prosperity_ore", "diamond"),
    ("prosperity_seed_base", "diamond"),
    ("prosperity_shard", "diamond"),
    ("prudentium_axe", "diamond_axe"),
    ("prudentium_block", "diamond"),
    ("prudentium_boots", "diamond_boots"),
    ("prudentium_bow", "bow"),
    ("prudentium_chestplate", "diamond_chestplate"),
    ("prudentium_crossbow", "diamond"),
    ("prudentium_essence", "diamond"),
    ("prudentium_farmland", "diamond"),
    ("prudentium_fishing_rod", "diamond"),
    ("prudentium_gemstone", "diamond"),
    ("prudentium_gemstone_block", "diamond"),
    ("prudentium_growth_accelerator", "diamond"),
    ("prudentium_helmet", "diamond_helmet"),
    ("prudentium_hoe", "diamond_hoe"),
    ("prudentium_ingot", "diamond"),
    ("prudentium_ingot_block", "diamond"),
    ("prudentium_leggings", "diamond_leggings"),
    ("prudentium_nugget", "diamond"),
    ("prudentium_pickaxe", "diamond_pickaxe"),
    ("prudentium_scythe", "diamond"),
    ("prudentium_shears", "diamond"),
    ("prudentium_shovel", "diamond_shovel"),
    ("prudentium_sickle", "diamond"),
    ("prudentium_spear", "diamond"),
    ("prudentium_staff", "diamond"),
    ("prudentium_sword", "diamond_sword"),
    ("prudentium_upgrade", "diamond"),
    ("prudentium_watering_can", "diamond"),
    ("pulsating_alloy_essence", "diamond"),
    ("pulsating_alloy_seeds", "wheat_seeds"),
    ("quartz_enriched_iron_essence", "diamond"),
    ("quartz_enriched_iron_seeds", "wheat_seeds"),
    ("queens_slime_essence", "diamond"),
    ("queens_slime_seeds", "wheat_seeds"),
    ("rabbit_essence", "diamond"),
    ("rabbit_seeds", "wheat_seeds"),
    ("redstone_alloy_essence", "diamond"),
    ("redstone_alloy_seeds", "wheat_seeds"),
    ("redstone_essence", "diamond"),
    ("redstone_seeds", "wheat_seeds"),
    ("refined_glowstone_essence", "diamond"),
    ("refined_glowstone_seeds", "wheat_seeds"),
    ("refined_obsidian_essence", "diamond"),
    ("refined_obsidian_seeds", "wheat_seeds"),
    ("rock_crystal_essence", "diamond"),
    ("rock_crystal_seeds", "wheat_seeds"),
    ("rose_gold_essence", "diamond"),
    ("rose_gold_seeds", "wheat_seeds"),
    ("rubber_essence", "diamond"),
    ("rubber_seeds", "wheat_seeds"),
    ("ruby_essence", "diamond"),
    ("ruby_seeds", "wheat_seeds"),
    ("saltpeter_essence", "diamond"),
    ("saltpeter_seeds", "wheat_seeds"),
    ("sapphire_essence", "diamond"),
    ("sapphire_seeds", "wheat_seeds"),
    ("sculk_essence", "diamond"),
    ("sculk_seeds", "wheat_seeds"),
    ("seed_reprocessor", "diamond"),
    ("sheep_essence", "diamond"),
    ("sheep_seeds", "wheat_seeds"),
    ("signalum_essence", "diamond"),
    ("signalum_seeds", "wheat_seeds"),
    ("silicon_essence", "diamond"),
    ("silicon_seeds", "wheat_seeds"),
    ("silver_essence", "diamond"),
    ("silver_seeds", "wheat_seeds"),
    ("skeleton_essence", "diamond"),
    ("skeleton_seeds", "wheat_seeds"),
    ("sky_stone_essence", "diamond"),
    ("sky_stone_seeds", "wheat_seeds"),
    ("slime_essence", "diamond"),
    ("slime_seeds", "wheat_seeds"),
    ("slimesteel_essence", "diamond"),
    ("slimesteel_seeds", "wheat_seeds"),
    ("slow_falling_augment", "diamond"),
    ("slowness_resistance_augment", "diamond"),
    ("soul_dust", "diamond"),
    ("soul_extractor", "diamond"),
    ("soul_glass", "diamond"),
    ("soul_jar", "diamond"),
    ("soularium_essence", "diamond"),
    ("soularium_seeds", "wheat_seeds"),
    ("soulium_block", "diamond"),
    ("soulium_dagger", "diamond"),
    ("soulium_dust", "diamond"),
    ("soulium_essence", "diamond"),
    ("soulium_gemstone", "diamond"),
    ("soulium_gemstone_block", "diamond"),
    ("soulium_ingot", "diamond"),
    ("soulium_ingot_block", "diamond"),
    ("soulium_nugget", "diamond"),
    ("soulium_ore", "diamond"),
    ("soulium_seed_base", "diamond"),
    ("soulium_seeds", "wheat_seeds"),
    ("soulium_spawner", "diamond"),
    ("soulstone", "diamond"),
    ("soulstone_bricks", "diamond"),
    ("soulstone_bricks_slab", "diamond"),
    ("soulstone_bricks_stairs", "diamond"),
    ("soulstone_bricks_wall", "diamond"),
    ("soulstone_chiseled_bricks", "diamond"),
    ("soulstone_cobble", "diamond"),
    ("soulstone_cobble_slab", "diamond"),
    ("soulstone_cobble_stairs", "diamond"),
    ("soulstone_cobble_wall", "diamond"),
    ("soulstone_cracked_bricks", "diamond"),
    ("soulstone_slab", "diamond"),
    ("soulstone_smooth", "diamond"),
    ("soulstone_smooth_slab", "diamond"),
    ("soulstone_stairs", "diamond"),
    ("speed_i_augment", "diamond"),
    ("speed_ii_augment", "diamond"),
    ("speed_iii_augment", "diamond"),
    ("spider_essence", "diamond"),
    ("spider_seeds", "wheat_seeds"),
    ("spirited_crystal_essence", "diamond"),
    ("spirited_crystal_seeds", "wheat_seeds"),
    ("squid_essence", "diamond"),
    ("squid_seeds", "wheat_seeds"),
    ("starmetal_essence", "diamond"),
    ("starmetal_seeds", "wheat_seeds"),
    ("steel_essence", "diamond"),
    ("steel_seeds", "wheat_seeds"),
    ("steeleaf_essence", "diamond"),
    ("steeleaf_seeds", "wheat_seeds"),
    ("step_assist_augment", "diamond"),
    ("stone_essence", "diamond"),
    ("stone_scythe", "diamond"),
    ("stone_seeds", "wheat_seeds"),
    ("stone_sickle", "diamond"),
    ("strength_i_augment", "diamond"),
    ("strength_ii_augment", "diamond"),
    ("strength_iii_augment", "diamond"),
    ("sulfur_essence", "diamond"),
    ("sulfur_seeds", "wheat_seeds"),
    ("supremium_axe", "diamond_axe"),
    ("supremium_block", "diamond"),
    ("supremium_boots", "diamond_boots"),
    ("supremium_bow", "bow"),
    ("supremium_chestplate", "diamond_chestplate"),
    ("supremium_crossbow", "diamond"),
    ("supremium_essence", "diamond"),
    ("supremium_farmland", "diamond"),
    ("supremium_fishing_rod", "diamond"),
    ("supremium_gemstone", "diamond"),
    ("supremium_gemstone_block", "diamond"),
    ("supremium_growth_accelerator", "diamond"),
    ("supremium_helmet", "diamond_helmet"),
    ("supremium_hoe", "diamond_hoe"),
    ("supremium_ingot", "diamond"),
    ("supremium_ingot_block", "diamond"),
    ("supremium_leggings", "diamond_leggings"),
    ("supremium_nugget", "diamond"),
    ("supremium_pickaxe", "diamond_pickaxe"),
    ("supremium_scythe", "diamond"),
    ("supremium_shears", "diamond"),
    ("supremium_shovel", "diamond_shovel"),
    ("supremium_sickle", "diamond"),
    ("supremium_spear", "diamond"),
    ("supremium_staff", "diamond"),
    ("supremium_sword", "diamond_sword"),
    ("supremium_upgrade", "diamond"),
    ("supremium_watering_can", "diamond"),
    ("terrasteel_essence", "diamond"),
    ("terrasteel_seeds", "wheat_seeds"),
    ("tertium_axe", "diamond_axe"),
    ("tertium_block", "diamond"),
    ("tertium_boots", "diamond_boots"),
    ("tertium_bow", "bow"),
    ("tertium_chestplate", "diamond_chestplate"),
    ("tertium_crossbow", "diamond"),
    ("tertium_essence", "diamond"),
    ("tertium_farmland", "diamond"),
    ("tertium_fishing_rod", "diamond"),
    ("tertium_gemstone", "diamond"),
    ("tertium_gemstone_block", "diamond"),
    ("tertium_growth_accelerator", "diamond"),
    ("tertium_helmet", "diamond_helmet"),
    ("tertium_hoe", "diamond_hoe"),
    ("tertium_ingot", "diamond"),
    ("tertium_ingot_block", "diamond"),
    ("tertium_leggings", "diamond_leggings"),
    ("tertium_nugget", "diamond"),
    ("tertium_pickaxe", "diamond_pickaxe"),
    ("tertium_scythe", "diamond"),
    ("tertium_shears", "diamond"),
    ("tertium_shovel", "diamond_shovel"),
    ("tertium_sickle", "diamond"),
    ("tertium_spear", "diamond"),
    ("tertium_staff", "diamond"),
    ("tertium_sword", "diamond_sword"),
    ("tertium_upgrade", "diamond"),
    ("tertium_watering_can", "diamond"),
    ("tilling_aoe_i_augment", "diamond"),
    ("tilling_aoe_ii_augment", "diamond"),
    ("tilling_aoe_iii_augment", "diamond"),
    ("tilling_aoe_iv_augment", "diamond"),
    ("tin_essence", "diamond"),
    ("tin_seeds", "wheat_seeds"),
    ("tinkering_table", "diamond"),
    ("turtle_essence", "diamond"),
    ("turtle_seeds", "wheat_seeds"),
    ("upgrade_base", "diamond"),
    ("uraninite_essence", "diamond"),
    ("uraninite_seeds", "wheat_seeds"),
    ("uranium_essence", "diamond"),
    ("uranium_seeds", "wheat_seeds"),
    ("vibrant_alloy_essence", "diamond"),
    ("vibrant_alloy_seeds", "wheat_seeds"),
    ("wand", "diamond"),
    ("water_agglomeratio", "diamond"),
    ("water_breathing_augment", "diamond"),
    ("water_essence", "diamond"),
    ("water_seeds", "wheat_seeds"),
    ("watering_can", "diamond"),
    ("weakness_resistance_augment", "diamond"),
    ("wither_resistance_augment", "diamond"),
    ("wither_skeleton_essence", "diamond"),
    ("wither_skeleton_seeds", "wheat_seeds"),
    ("witherproof_block", "diamond"),
    ("witherproof_bricks", "diamond"),
    ("witherproof_glass", "diamond"),
    ("wood_essence", "diamond"),
    ("wood_seeds", "wheat_seeds"),
    ("wooden_scythe", "diamond"),
    ("wooden_sickle", "diamond"),
    ("yellorium_essence", "diamond"),
    ("yellorium_seeds", "wheat_seeds"),
    ("zinc_essence", "diamond"),
    ("zinc_seeds", "wheat_seeds"),
    ("zombie_essence", "diamond"),
    ("zombie_seeds", "wheat_seeds"),
];

/// Every menu type the mod registers, from `ModMenuTypes`.
pub const MENU_TYPES: [&str; 8] = [
    "enchanter",
    "furnace",
    "harvester",
    "ore_infuser",
    "reprocessor",
    "soul_extractor",
    "soulium_spawner",
    "tinkering_table",
];

/// Every block entity type the mod registers, from `ModTileEntities`.
pub const BLOCK_ENTITY_TYPES: [&str; 13] = [
    "awakening_altar",
    "awakening_pedestal",
    "enchanter",
    "essence_vessel",
    "furnace",
    "harvester",
    "infusion_altar",
    "infusion_pedestal",
    "ore_infuser",
    "seed_reprocessor",
    "soul_extractor",
    "soulium_spawner",
    "tinkering_table",
];
